VRNIOP-3814: Adding Databus enhanced client
vmware/network-insight-sdk-python pull request #52
Opened 2022-09-21 04:22 UTC by prasadinglearkin

2022-09-28 10:32 UTC, cnayakarkin reviewed
will continue.. please address comments till now

2022-09-28 10:32 UTC, cnayakarkin commented on databus_client/queues/filters/metric_filter.py
> +    def pass_metric_filter(self, source=None, entry=None, message_group=None):
convert to static. Other methods as well.

2022-09-28 10:32 UTC, cnayakarkin commented on databus_client/queues/entity_queues/databus_metric_queue.py
> +                    metric_filter = MetricFilter()
import and call directly

2022-09-28 10:34 UTC, cnayakarkin requested changes
address previous comments

2022-09-28 10:34 UTC, cnayakarkin commented on databus_client/queues/filter_manager.py
> +    def set_filters(self, filter_dict=None):
convert to singleton and maintain one copy of lookup dict

2023-09-25 12:02 UTC, cnayakarkin approved these changes
LGTM

2023-09-25 12:03 UTC, prasadinglearkin commented on databus_client/README.MD
> +Start docker container with the image
Done

2023-09-25 12:06 UTC, prasadinglearkin commented on databus_client/endpoint/client_endpoint.py
> +                result = f_manager.get_problems_filter(source=source)
Done

2023-09-25 12:06 UTC, merged