Adding checks for None for flows is_filtered flag
vmware/network-insight-sdk-python pull request #63
Opened 2023-12-19 04:56 UTC by Sonamsinhaarkin

Epic:
https://jira.eng.vmware.com/browse/CYG-85319

Tracking Jira:
https://jira.eng.vmware.com/browse/CYG-93282

Summary:
Adding checks for None for flows is_filtered flag

2023-12-19 05:47 UTC, prasadinglearkin requested changes

2023-12-19 05:47 UTC, prasadinglearkin commented on databus_client/queues/entity_queues/databus_flows_queue.py
> +                            if is_filtered is not None:
if is_filtered
only this shall work

2023-12-19 05:47 UTC, prasadinglearkin commented on databus_client/endpoint/client_endpoint.py
> +    return databus_queue_processor(request=request, message_group=DatabusMessageGroup.FLOWS.value, is_filtered=False)
Not needed

2023-12-19 05:47 UTC, prasadinglearkin commented on databus_client/endpoint/client_endpoint.py
> +        if is_filtered is not None:
Not needed

2023-12-19 06:48 UTC, Sonamsinhaarkin commented on databus_client/queues/entity_queues/databus_flows_queue.py
> +                            if is_filtered is not None:
changes done

2023-12-19 06:48 UTC, Sonamsinhaarkin commented on databus_client/endpoint/client_endpoint.py
> +    return databus_queue_processor(request=request, message_group=DatabusMessageGroup.FLOWS.value, is_filtered=False)
changes done

2023-12-19 06:48 UTC, Sonamsinhaarkin commented on databus_client/endpoint/client_endpoint.py
> +        if is_filtered is not None:
changes done

2023-12-21 11:35 UTC, prasadinglearkin approved these changes

2023-12-21 11:44 UTC, merged